version: '3.0'

services:
  db:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .:/home/node/postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge

  app:
    build: .
    tty: true
    entrypoint: dockerize -wait tcp://db:5432 -timeout 30s ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
